version: '3'
services:
  db:
    image: mongo
    container_name: gabeya-postgres
    restart: always
    environment:
      - MONGO_DB=gabeya
      - MONGO_USER=mongo
      - MONGO_PASSWORD=mongo

  gabeya_api:
    command: bash -c "yarn db:refresh && yarn dev"
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./:/usr/src/app
    container_name: gabeya-backend
    depends_on:
      - db
    ports:
      - '${PORT}:${PORT}'
    env_file: ./env
    environment:
      DATABASE_URL: mongo://mongo:mongo@db:5432/gabeya