version: '3'
services:
  db:
    image: mysql:latest
    container_name: gabeya-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=GABEYA
      - MYSQL_USER=users_service
      - MYSQL_PASSWORD=123
    ports:
      - '${DB_PORT}:3306'

  gabeya_api:
    command: bash -c "yarn dev"
    build: .
    volumes:
      - ./:/usr/src/app
    container_name: gabeya-backend
    depends_on:
      - db
    ports:
      - '${PORT}:${PORT}'
    env_file: .env
    environment:
      DATABASE_HOST: gabeya-mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: GABEYA
      MYSQL_USER: users_service
      MYSQL_PASSWORD: 123
      PORT: 5000
      DB_PORT: 33060
